"""
In-memory analysis snapshot cache.

Design intent:
- Each run_id maps to ONE authoritative analysis snapshot.
- Snapshot is generated by analysis_engine.run_full_analysis().
- Snapshot may be overwritten for the SAME run_id (intentional).
- Used to prevent stale dashboards and cross-run contamination.

Scope:
- Single-process / lab / SOC simulation use.
- NOT thread-safe or multi-worker safe by design.
- In production, replace with Redis / task-result store.
"""

from typing import Dict, Optional

# -------------------------------------------------------------------
# Internal store
# -------------------------------------------------------------------

_ANALYSIS_STORE: Dict[str, dict] = {}  # { run_id: analysis_context }


# -------------------------------------------------------------------
# Snapshot API
# -------------------------------------------------------------------

def set_analysis_snapshot(run_id: str, snapshot: dict) -> None:
    """
    Store analysis snapshot for a specific run_id.

    Behavior:
    - Overwrites snapshot if the same run_id is reused.
    - This is intentional: dashboard is the single source of truth.
    """
    if not run_id:
        return

    if snapshot is None:
        return

    _ANALYSIS_STORE[run_id] = snapshot


def get_analysis_snapshot(run_id: str) -> Optional[dict]:
    """
    Retrieve analysis snapshot for a run_id.

    Returns:
    - dict if snapshot exists
    - None if not found or run_id is invalid
    """
    if not run_id:
        return None

    return _ANALYSIS_STORE.get(run_id)


def clear_analysis_snapshot(run_id: Optional[str] = None, *, clear_all: bool = False) -> None:
    """
    Clear cached analysis snapshots.

    Modes:
    - run_id provided → clears only that run's snapshot
    - clear_all=True  → clears ALL snapshots (explicit only)

    Safety:
    - Global wipe requires explicit clear_all=True
    - Prevents accidental cross-session destruction
    """
    if run_id:
        _ANALYSIS_STORE.pop(run_id, None)
        return

    if clear_all:
        _ANALYSIS_STORE.clear()


# -------------------------------------------------------------------
# Diagnostics / Debug (optional but useful)
# -------------------------------------------------------------------

def _debug_cache_state() -> dict:
    """
    INTERNAL USE ONLY.
    Returns cache metadata for debugging.
    """
    return {
        "total_runs": len(_ANALYSIS_STORE),
        "run_ids": list(_ANALYSIS_STORE.keys()),
    }
